### ISSUE TITLE
error installing with composer

### ISSUE THREAD

**Issue by giggty** [zachweix/PhpZmanim#11]
i tried installing with composer and i get the foloowing error

Composer could not detect the root package (zachweix/php-zmanim) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Root package 'zachweix/php-zmanim' cannot require itself in its composer.json

![Untitled](https://github.com/user-attachments/assets/762d7e29-12f7-4ba4-9f07-491f3964a4a8)

i'm following this turturial
https://hackernoon.com/time-data-series-a-beginners-guide-to-php-zmanim
plz help :)

**Comment by giggty** [comment]
nevermind .... forgot to delete current composer file....

**Comment by zachweix** [comment]
Glad to hear you had no more issues. I was just testing to see if something changed
