### ISSUE TITLE
Yom Tov

### ISSUE THREAD

**Issue by shmaltz** [zachweix/PhpZmanim#6]
First, thanks for the PHP port!

Is it possible to check if the current day is yom tov with this library?

Thanks!

**Comment by zachweix** [comment]
Currently the port is only for calculating times of day (alos, tzais etc.). In order to get what you're looking for, I would recommend using the https://github.com/zmanim/zman library

**Comment by shmaltz** [comment]
Thank you, I'll check that out.
Chag Sameach
