### ISSUE TITLE
Boolean is_asir_baseiass_meloche

### ISSUE THREAD

**Issue by sbr5136014** [zachweix/PhpZmanim#7]
is there in PHP this Boolean 
צו עס איז אסור בעשיית מלכאה?

**Comment by zachweix** [comment]
This library only calculates Zmanim times, such as sunrise and sunset. It does not calculate the Jewish Calendar part of the library. If you want to do something like that, you can integrate with the Zmanim/Zman library (https://github.com/zmanim/zman)
