### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by shmaltz** [zachweix/PhpZmanim#8]
Hi, thanks for this wonderful library!

Is it possible to generate the timezone automatically from the lat/long coordinates?

**Comment by zachweix** [comment]
There might be a library to do that in PHP, which you can use to integrate with this, but nothing is built in to the library

**Comment by shmaltz** [comment]
I was asking because in the docs I saw something regarding geolocation, but I guess it doesn't do what I need. Thanks!
