### ISSUE TITLE
Error in Calculator

### ISSUE THREAD

**Issue by HaLeiVi** [zachweix/PhpZmanim#9]
I am getting this error on my first run:
"double" will be interpreted as a class name. Did you mean "float"? Write "\PhpZmanim\Calculator\double" or import the class with "use" to suppress this warning in /home/main/public_html/zmanim/vendor/zachweix/php-zmanim/src/Calculator/AstronomicalCalculator.php on line 73

**Comment by HaLeiVi** [comment]
I changed all (double)s to (float) and all is fine. Until I try getSofZmanTfilaMGA(). I get: `PHP Fatal error:  Uncaught Error: Call to undefined method PhpZmanim\Zmanim::getShaahZmanisMGA()`. However, getSofZmanTfilaGra Does work.

It seems like any function that utilizes $this->getTzais72() fails. I do not know why. It works in my instance of Zmanim but not internally.

**Comment by HaLeiVi** [comment]
Oh. Now I see. The downloaded version has a function called getSofZmanShmaMGA, but what gets installed through Composer only has getSofZmanShmaMA, which seems to marked for deprecation.

**Comment by rbzachary** [comment]
Make sure that you're using the latest version in composer - v1.3. In my projects that use composer I have `getSofZmanShmaMGA`
